### ISSUE TITLE
fact.path, how to trat float nan?

### ISSUE THREAD

**Issue by relleums** [fact-project/pyfact#76]
Currently float ```nan``` is not a valid input for ```fact.path.template_to_path```:

```
night = '20161213', run = nan, template = '/home/sebastian/Desktop/phs_production/fact/raw/{Y}/{M}/{D}/{N}_{R}.drs.fits.gz', kwargs = {}

    def template_to_path(night, run, template, **kwargs):
        '''Make path from template and (night, run) using kwargs existing.
    
        night: int or string
            e.g. night = 20160102 (int)
            is used to create Y,M,D,N template values as:
            Y = "2016"
            M = "01"
            D = "02"
            N = "20160101"
        run: int or string
            e.g. run = 1  or run = "000000001"
            is used to create template value R = "001"
        template: string
            e.g. "/foo/bar/{Y}/baz/{R}_{M}_{D}.gz.{N}"
        kwargs:
            if template contains other place holders than Y,M,D,N,R
            kwargs are used to format these.
        '''
        night = str(night)
        if run is not None:
>           kwargs['R'] = '{:03d}'.format(int(run))
E           VatlueError: cannot convert float NaN to integer

../../../../anaconda3/lib/python3.5/site-packages/fact/path.py:32: ValueError
```

I wonder if this ValueError is what we want. In my case, it would be fine to return a not existing path a ```nap``` so to speak (maybe /dev/null?). But I am not sure yet.

**Comment by dneise** [comment]
These functions in `fact.path` are in my opinion not useful yet, they are just good for **building** something useful, without doing many string manipulations.

I for example use `functools.partial` very often to avoid repetitions, like this:

```python
from functools import partial
from fact.path import template_to_path

phs_path_generator = partial(
    template_to_path, 
    template =  '/home/sebastian/Desktop/phs_production/fact/raw/{Y}/{M}/{D}/{N}_{R}.drs.fits.gz')
```

In your case, this `phs_path_generator` would not help much, but what about this one?

```python
def phs_path_generator(night, run):
    template =  '/home/sebastian/Desktop/phs_production/fact/raw/{Y}/{M}/{D}/{N}_{R}.drs.fits.gz'
    try:
        return template_to_path(night, run, template)
    except ValueError:
        return '/some/not/a/path/thing'
```

I think having floats as night or run is not a common case, so supporting it would bloat up the code.
I think even accepting ints **and** strings was a mistake. ints is all to be supported. The rest can be done by the user of these functions. 

Even if having floats for night and run was a usual use-case, then I would find it difficult to define a good return value for `run=float('nan')` or `night=float('nan')`. Since we do not know what the user wants to do with the path later. 

If it is intended to be an output path, then returning `/dev/null` would result in no exception, but the user would not get an output file, which might be very surprising. 

If it was intended to be an input path, then after generating the path,there might be a check if the input file exists. `os.path.exists('/dev/null')` returns `True`, which in my use case would mean, that I have all reason to believe that my analysis will run without any error, so I submit it to qsub. However, in this case it will fail immediately and I'd rather had not submitted it, but gotten an exception that tells me, that I tried to generate a path from nan.

**Comment by maxnoe** [comment]
I also believe that a `ValueError` is the most sane thing to do for float input for these functions.

**Comment by relleums** [comment]
I agree with you guys, returning a ```nan``` like path is not a good idea. If  ```fact.path.template_to_path``` will be restricted to ```int```, this got solved anyhow.

**Comment by dneise** [comment]
Solves
